name: Sync Upstream Release

on:
  workflow_dispatch:

env:
  UPSTREAM_REPO: strongtz/edl-ng
  PROJECT_NAME: edl-ng

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for new release
        id: check
        run: |
          latest=$(curl -s https://api.github.com/repos/${{ env.UPSTREAM_REPO }}/releases/latest | jq -r '.tag_name')
          version=${latest#v}

          if git tag | grep -q "^v$version$"; then
            echo "Tag v$version already exists, skipping"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "New version found: v$version"
            echo "skip=false" >> $GITHUB_OUTPUT
            echo "tag=$latest" >> $GITHUB_OUTPUT
            echo "version=$version" >> $GITHUB_OUTPUT
          fi

      - name: Download release asset
        if: steps.check.outputs.skip == 'false'
        uses: robinraju/release-downloader@v1
        with:
          repository: ${{ env.UPSTREAM_REPO }}
          tag: ${{ steps.check.outputs.tag }}
          fileName: ${{ env.PROJECT_NAME }}.${{ steps.check.outputs.version }}.linux-arm64.deb

      - name: Create release
        if: steps.check.outputs.skip == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.check.outputs.version }}
          name: ${{ env.PROJECT_NAME }} v${{ steps.check.outputs.version }}
          body: Synced from https://github.com/${{ env.UPSTREAM_REPO }}/releases/tag/${{ steps.check.outputs.tag }}
          files: ${{ env.PROJECT_NAME }}.${{ steps.check.outputs.version }}.linux-arm64.deb
